/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace NFTAuction {
      
    export type AuctionStruct = {auctionId: BigNumberish, nftContract: AddressLike, tokenId: BigNumberish, seller: AddressLike, startingPrice: BigNumberish, highestBid: BigNumberish, highestBidder: AddressLike, endTime: BigNumberish, ended: boolean, cancelled: boolean}

    export type AuctionStructOutput = [auctionId: bigint, nftContract: string, tokenId: bigint, seller: string, startingPrice: bigint, highestBid: bigint, highestBidder: string, endTime: bigint, ended: boolean, cancelled: boolean] & {auctionId: bigint, nftContract: string, tokenId: bigint, seller: string, startingPrice: bigint, highestBid: bigint, highestBidder: string, endTime: bigint, ended: boolean, cancelled: boolean }
  

    export type BidStruct = {bidder: AddressLike, amount: BigNumberish, timestamp: BigNumberish}

    export type BidStructOutput = [bidder: string, amount: bigint, timestamp: bigint] & {bidder: string, amount: bigint, timestamp: bigint }
  
    }

  export interface NFTAuctionInterface extends Interface {
    getFunction(nameOrSignature: "ANTI_SNIPE_EXTENSION" | "ANTI_SNIPE_WINDOW" | "MAX_DURATION" | "MAX_PLATFORM_FEE" | "MIN_BID_INCREMENT_BPS" | "MIN_DURATION" | "auctions" | "cancelAuction" | "createAuction" | "endAuction" | "fetchActiveAuctions" | "getAuctionBids" | "owner" | "placeBid" | "platformFee" | "renounceOwnership" | "setPlatformFee" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionCancelled" | "AuctionCreated" | "AuctionEnded" | "BidPlaced" | "OwnershipTransferred" | "PlatformFeeUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'ANTI_SNIPE_EXTENSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'ANTI_SNIPE_WINDOW', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PLATFORM_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_BID_INCREMENT_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fetchActiveAuctions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuctionBids', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'platformFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ANTI_SNIPE_EXTENSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ANTI_SNIPE_WINDOW', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PLATFORM_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_BID_INCREMENT_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchActiveAuctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuctionBids', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace AuctionCancelledEvent {
      export type InputTuple = [auctionId: BigNumberish];
      export type OutputTuple = [auctionId: bigint];
      export interface OutputObject {auctionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionCreatedEvent {
      export type InputTuple = [auctionId: BigNumberish, nftContract: AddressLike, tokenId: BigNumberish, seller: AddressLike, startingPrice: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [auctionId: bigint, nftContract: string, tokenId: bigint, seller: string, startingPrice: bigint, endTime: bigint];
      export interface OutputObject {auctionId: bigint, nftContract: string, tokenId: bigint, seller: string, startingPrice: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionEndedEvent {
      export type InputTuple = [auctionId: BigNumberish, winner: AddressLike, amount: BigNumberish, platformFeeAmount: BigNumberish, royaltyAmount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, winner: string, amount: bigint, platformFeeAmount: bigint, royaltyAmount: bigint];
      export interface OutputObject {auctionId: bigint, winner: string, amount: bigint, platformFeeAmount: bigint, royaltyAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish, newEndTime: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint, newEndTime: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint, newEndTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NFTAuction extends BaseContract {
    
    connect(runner?: ContractRunner | null): NFTAuction;
    waitForDeployment(): Promise<this>;

    interface: NFTAuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ANTI_SNIPE_EXTENSION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ANTI_SNIPE_WINDOW: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PLATFORM_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_BID_INCREMENT_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, bigint, bigint, string, bigint, boolean, boolean] & {auctionId: bigint, nftContract: string, tokenId: bigint, seller: string, startingPrice: bigint, highestBid: bigint, highestBidder: string, endTime: bigint, ended: boolean, cancelled: boolean }],
      'view'
    >
    

    
    cancelAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createAuction: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, startingPrice: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fetchActiveAuctions: TypedContractMethod<
      [],
      [NFTAuction.AuctionStructOutput[]],
      'view'
    >
    

    
    getAuctionBids: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [NFTAuction.BidStructOutput[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBid: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    platformFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPlatformFee: TypedContractMethod<
      [fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ANTI_SNIPE_EXTENSION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ANTI_SNIPE_WINDOW'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PLATFORM_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_BID_INCREMENT_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, bigint, bigint, string, bigint, boolean, boolean] & {auctionId: bigint, nftContract: string, tokenId: bigint, seller: string, startingPrice: bigint, highestBid: bigint, highestBidder: string, endTime: bigint, ended: boolean, cancelled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'cancelAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, startingPrice: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fetchActiveAuctions'): TypedContractMethod<
      [],
      [NFTAuction.AuctionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAuctionBids'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [NFTAuction.BidStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBid'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'platformFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPlatformFee'): TypedContractMethod<
      [fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuctionCancelled'): TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
getEvent(key: 'AuctionCreated'): TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
getEvent(key: 'AuctionEnded'): TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PlatformFeeUpdated'): TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;

    filters: {
      
      'AuctionCancelled(uint256)': TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
      AuctionCancelled: TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
    

      'AuctionCreated(uint256,address,uint256,address,uint256,uint256)': TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
      AuctionCreated: TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
    

      'AuctionEnded(uint256,address,uint256,uint256,uint256)': TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
      AuctionEnded: TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
    

      'BidPlaced(uint256,address,uint256,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PlatformFeeUpdated(uint96,uint96)': TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
      PlatformFeeUpdated: TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
    
    };
  }