/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace NFTMarketplace {
      
    export type ListingStruct = {listingId: BigNumberish, nftContract: AddressLike, tokenId: BigNumberish, seller: AddressLike, price: BigNumberish, active: boolean, listedAt: BigNumberish}

    export type ListingStructOutput = [listingId: bigint, nftContract: string, tokenId: bigint, seller: string, price: bigint, active: boolean, listedAt: bigint] & {listingId: bigint, nftContract: string, tokenId: bigint, seller: string, price: bigint, active: boolean, listedAt: bigint }
  
    }

  export interface NFTMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "MAX_PLATFORM_FEE" | "buyNFT" | "cancelListing" | "fetchListingsByOwner" | "fetchMarketItems" | "listNFT" | "listings" | "owner" | "pause" | "paused" | "platformFee" | "renounceOwnership" | "setPlatformFee" | "transferOwnership" | "unpause" | "updatePrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ListingCancelled" | "NFTListed" | "NFTSold" | "OwnershipTransferred" | "Paused" | "PlatformFeeUpdated" | "PriceUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_PLATFORM_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyNFT', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fetchListingsByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'fetchMarketItems', values?: undefined): string;
encodeFunctionData(functionFragment: 'listNFT', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePrice', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MAX_PLATFORM_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchListingsByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchMarketItems', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePrice', data: BytesLike): Result;
  }

  
    export namespace ListingCancelledEvent {
      export type InputTuple = [listingId: BigNumberish];
      export type OutputTuple = [listingId: bigint];
      export interface OutputObject {listingId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NFTListedEvent {
      export type InputTuple = [listingId: BigNumberish, nftContract: AddressLike, tokenId: BigNumberish, seller: AddressLike, price: BigNumberish];
      export type OutputTuple = [listingId: bigint, nftContract: string, tokenId: bigint, seller: string, price: bigint];
      export interface OutputObject {listingId: bigint, nftContract: string, tokenId: bigint, seller: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NFTSoldEvent {
      export type InputTuple = [listingId: BigNumberish, buyer: AddressLike, price: BigNumberish, platformFeeAmount: BigNumberish, royaltyAmount: BigNumberish];
      export type OutputTuple = [listingId: bigint, buyer: string, price: bigint, platformFeeAmount: bigint, royaltyAmount: bigint];
      export interface OutputObject {listingId: bigint, buyer: string, price: bigint, platformFeeAmount: bigint, royaltyAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceUpdatedEvent {
      export type InputTuple = [listingId: BigNumberish, oldPrice: BigNumberish, newPrice: BigNumberish];
      export type OutputTuple = [listingId: bigint, oldPrice: bigint, newPrice: bigint];
      export interface OutputObject {listingId: bigint, oldPrice: bigint, newPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NFTMarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): NFTMarketplace;
    waitForDeployment(): Promise<this>;

    interface: NFTMarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_PLATFORM_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyNFT: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    cancelListing: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fetchListingsByOwner: TypedContractMethod<
      [ownerAddr: AddressLike, ],
      [NFTMarketplace.ListingStructOutput[]],
      'view'
    >
    

    
    fetchMarketItems: TypedContractMethod<
      [],
      [NFTMarketplace.ListingStructOutput[]],
      'view'
    >
    

    
    listNFT: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    listings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, bigint, boolean, bigint] & {listingId: bigint, nftContract: string, tokenId: bigint, seller: string, price: bigint, active: boolean, listedAt: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    platformFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPlatformFee: TypedContractMethod<
      [fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updatePrice: TypedContractMethod<
      [listingId: BigNumberish, newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_PLATFORM_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyNFT'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fetchListingsByOwner'): TypedContractMethod<
      [ownerAddr: AddressLike, ],
      [NFTMarketplace.ListingStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'fetchMarketItems'): TypedContractMethod<
      [],
      [NFTMarketplace.ListingStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'listNFT'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, bigint, boolean, bigint] & {listingId: bigint, nftContract: string, tokenId: bigint, seller: string, price: bigint, active: boolean, listedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'platformFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPlatformFee'): TypedContractMethod<
      [fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePrice'): TypedContractMethod<
      [listingId: BigNumberish, newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ListingCancelled'): TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
getEvent(key: 'NFTListed'): TypedContractEvent<NFTListedEvent.InputTuple, NFTListedEvent.OutputTuple, NFTListedEvent.OutputObject>;
getEvent(key: 'NFTSold'): TypedContractEvent<NFTSoldEvent.InputTuple, NFTSoldEvent.OutputTuple, NFTSoldEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PlatformFeeUpdated'): TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
getEvent(key: 'PriceUpdated'): TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'ListingCancelled(uint256)': TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
      ListingCancelled: TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
    

      'NFTListed(uint256,address,uint256,address,uint256)': TypedContractEvent<NFTListedEvent.InputTuple, NFTListedEvent.OutputTuple, NFTListedEvent.OutputObject>;
      NFTListed: TypedContractEvent<NFTListedEvent.InputTuple, NFTListedEvent.OutputTuple, NFTListedEvent.OutputObject>;
    

      'NFTSold(uint256,address,uint256,uint256,uint256)': TypedContractEvent<NFTSoldEvent.InputTuple, NFTSoldEvent.OutputTuple, NFTSoldEvent.OutputObject>;
      NFTSold: TypedContractEvent<NFTSoldEvent.InputTuple, NFTSoldEvent.OutputTuple, NFTSoldEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PlatformFeeUpdated(uint96,uint96)': TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
      PlatformFeeUpdated: TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
    

      'PriceUpdated(uint256,uint256,uint256)': TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
      PriceUpdated: TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }